# Generated by Django 2.0.13 on 2020-07-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YEAR', models.IntegerField(default=0)),
                ('MONTH', models.IntegerField(default=0)),
                ('DAY', models.IntegerField(default=0)),
                ('DAY_OF_WEEK', models.IntegerField(default=0)),
                ('AIRLINE', models.CharField(max_length=200)),
                ('FLIGHT_NUMBER', models.IntegerField(default=0)),
                ('TAIL_NUMBER', models.CharField(max_length=200)),
                ('ORIGIN_AIRPORT', models.CharField(max_length=200)),
                ('DESTINATION_AIRPORT', models.CharField(max_length=200)),
                ('SCHEDULED_DEPARTURE', models.IntegerField(default=0)),
                ('DEPARTURE_TIME', models.IntegerField(default=0)),
                ('DEPARTURE_DELAY', models.IntegerField(default=0)),
                ('TAXI_OUT', models.IntegerField(default=0)),
                ('WHEELS_OFF', models.IntegerField(default=0)),
                ('SCHEDULED_TIME', models.IntegerField(default=0)),
                ('ELAPSED_TIME', models.IntegerField(default=0)),
                ('AIR_TIME', models.IntegerField(default=0)),
                ('DISTANCE', models.IntegerField(default=0)),
                ('WHEELS_ON', models.IntegerField(default=0)),
                ('TAXI_IN', models.IntegerField(default=0)),
                ('SCHEDULED_ARRIVAL', models.IntegerField(default=0)),
                ('ARRIVAL_TIME', models.IntegerField(default=0)),
                ('ARRIVAL_DELAY', models.IntegerField(default=0)),
                ('DIVERTED', models.IntegerField(default=0)),
                ('CANCELLED', models.IntegerField(default=0)),
                ('CANCELLATION_REASON', models.IntegerField(default=0)),
                ('AIR_SYSTEM_DELAY', models.IntegerField(default=0)),
                ('SECURITY_DELAY', models.IntegerField(default=0)),
                ('AIRLINE_DELAY', models.IntegerField(default=0)),
                ('LATE_AIRCRAFT_DELAY', models.IntegerField(default=0)),
                ('WEATHER_DELAY', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'FlighDelayData',
            },
        ),
    ]
